version: "3.9"
services:
  ######## Webserver
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    depends_on:
      - php72
      - php73
      - php74
      - php80
      - php81
      - imgproxy
    ports:
      - 80:80
      - 443:443
    networks:
      webdev:
        aliases:
          - d10.localhost
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./vhosts:/etc/nginx/sites
      - ./sites:/var/www/html/
      - ~/Sites:/Sites/
      - ~/Sites:${HOME}/Sites
      - ~/Repositories:${HOME}/Repositories
      - ./certs:/etc/nginx/certs
      # - tmp:/tmp
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
    extra_hosts:
      - host.docker.internal:host-gateway
  ######## PHP
  php82:
    container_name: php82
    image: wodby/php:8.2-dev
    extends: 
      file: php.yml
      service: php
    env_file:
      - config/php82.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  php81:
    container_name: php81
    image: wodby/php:8.1-dev
    extends: 
      file: php.yml
      service: php
    env_file:
      - config/php81.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  php80:
    container_name: php80
    image: wodby/php:8.0-dev
    extends: 
      file: php.yml
      service: php
    env_file:
      - config/php80.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  php74:
    container_name: php74
    image: wodby/php:7.4-dev
    extends: 
      file: php.yml
      service: php
    env_file:
      - config/php74.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  php73:
    container_name: php73
    image: wodby/php:7.3-dev
    extends: 
      file: php.yml
      service: php
    env_file:
      - config/php73.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  php72:
    container_name: php72
    image: wodby/php:7.2-dev
    extends: 
      file: php.yml
      service: php
    env_file:
      - config/php72.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  ######## Database
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
      # - tmp:/tmp
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    networks:
      - webdev
    ports:
      - 3306:3306
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  # mysql:
  #   container_name: mysql
  #   image: mysql:5.7
  #   restart: unless-stopped
  #   volumes:
  #     - mysql:/var/lib/mysql
  #     - tmp:/tmp
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #     # MYSQL_USER: root
  #     # MYSQL_PASSWORD: ''
  #     # MYSQL_TCP_PORT: 13306
  #   networks:
  #     - webdev
  #   ports:
  #     - 3306:3306
  #   labels:
  #     - com.centurylinklabs.watchtower.scope=webdev
  ######## Misc
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
    networks:
      - webdev
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  imgproxy:
    container_name: imgproxy
    image: darthsim/imgproxy:latest
    restart: unless-stopped
    # networks:
    #   - webdev
    network_mode: host
    env_file:
      - config/imgproxy.env
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      - webdev
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup --scope webdev
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - TZ=Europe/Berlin
    volumes:
      - vaultwarden:/data
    ports:
      - 8123:80
      - 3012:3012
    networks:
      - webdev
    labels:
      - com.centurylinklabs.watchtower.scope=webdev
  # busybox:
  #   container_name: busybox
  #   image: busybox
  #   tty: true
  #   networks:
  #     - webdev
  #   dns_search:
  #     nginx
networks:
  webdev:

volumes:
  mariadb:
    name: mariadb
  mysql:
    name: mysql
  tmp:
    name: webdev_tmp
  portainer:
    name: webdev_portainer
  vaultwarden:
    name: webdev_vaultwarden